package services.OrderManager;


public enum OrderStatus {
    INITIATED,
    PAYMENT_SUCCESSFUL,
    ACCEPTED,
    PREPARING_ORDER,
    PREPARED,
    READY_FOR_PICKUP,
    FAILED,
    CANCELLED,
    DELIVERED,
    PAYMENT_REFUNDED,
    ORDER_PICKED_BY_DELIVERY_PARTNER,
    DELIVERY_PARTNER_ON_THE_WAY_TO_RESTAURANT,
    DELIVERY_PARTNER_ON_THE_WAY_TO_CUSTOMER_LOCATION,
    DELIVER_PARTNER_AT_CUSTOMER_LOCATION,
    DELIVERY_PARTNER_AT_RESTAURANT
}