package services.DeliveryManager.domainObjects;



public enum OrderDeliveryStatus {
    ASSIGN_DELIVERY_AGENT_IN_PROGRESS,
    DELIVERY_AGENT_ASSIGNED,
    DELIVERY_AGENT_ON_THE_WAY_TO_RES,
    DELIVERY_AGENT_ON_THE_WAY_TO_DELIVERY_LOCATION,
    DELIVERY_AGENT_ARRIVED_AT_RES,
    DELIVERY_AGENT_PICKED_ORDER_FROM_RES,
    DELIVERY_AGENT_ARRIVED_AT_CUSTOMER_LOCATION,
    DELIEVRY_AGENT_HAS_DELIVERED_THE_ORDER
}